import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'fr' | 'en' | 'ar';

const T = {
  fr: {
    // Nav & shared
    teachers: 'Tuteurs', courses: 'Cours', login: 'Connexion', register: 'Inscription',
    dashboard: 'Tableau de bord', logout: 'Déconnexion', profile: 'Profil', sessions: 'Mes séances',
    myCourses: 'Mes cours', availability: 'Disponibilités', users: 'Utilisateurs',
    aiTutor: 'IA Tutor', home: 'Accueil', notifications: 'Notifications',

    // Home
    heroTagline: 'Plateforme de soutien scolaire #1 en France',
    heroTitle1: 'Maîtrisez votre avenir', heroTitle2: 'avec un', heroTitle3: 'tuteur expert',
    heroSubtitle: 'Connectez-vous avec des enseignants qualifiés pour des séances personnalisées. Parce que chaque élève mérite d\'atteindre son plein potentiel.',
    startFree: 'Commencer gratuitement', seeTutors: 'Voir les tuteurs',
    verifiedTeachers: 'Enseignants vérifiés', flexibleHours: 'Horaires flexibles', provenResults: 'Résultats prouvés',
    whyChoose: 'Pourquoi choisir EduPlatform ?', whySubtitle: 'Une expérience d\'apprentissage complète, personnalisée et efficace.',
    ctaTitle: 'Prêt à commencer ?', ctaSubtitle: 'Rejoignez des milliers d\'élèves qui progressent avec EduPlatform.',
    createFreeAccount: 'Créer un compte gratuit',
    allRights: 'Tous droits réservés.',

    // Login
    welcome: 'Bienvenue', loginSubtitle: 'Connectez-vous à votre compte',
    password: 'Mot de passe', signIn: 'Se connecter', signingIn: 'Connexion…',
    noAccount: 'Pas de compte ?', signUpLink: 'S\'inscrire',
    demoAccountsLabel: 'Comptes de démo :',
    invalidCredentials: 'Email ou mot de passe incorrect.',
    fillFields: 'Veuillez remplir tous les champs.',
    loginSuccess: 'Connexion réussie !',

    // Register
    createAccount: 'Créer un compte', joinToday: 'Rejoignez EduPlatform dès aujourd\'hui',
    firstName: 'Prénom', lastName: 'Nom',
    iAm: 'Je suis', studentRole: 'Élève / Étudiant', teacherRole: 'Enseignant / Tuteur', parentRole: 'Parent',
    creating: 'Inscription…', createMyAccount: 'Créer mon compte',
    alreadyMember: 'Déjà inscrit ?', signInLink: 'Se connecter',
    minChars: 'Min. 8 caractères', accountCreated: 'Compte créé avec succès !',

    // Profile
    myProfile: 'Mon profil', profileSubtitle: 'Gérez vos informations personnelles',
    personalInfo: 'Informations personnelles',
    phoneNumber: 'Téléphone', biography: 'Biographie',
    bioPlaceholder: 'Parlez-nous de vous…',
    saving: 'Sauvegarde…', save: 'Sauvegarder',
    profileUpdated: '✓ Profil mis à jour avec succès',
    changePassword: 'Changer le mot de passe', newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer', repeatPassword: 'Répéter le mot de passe',
    changeBtn: 'Changer', passwordChanged: 'Mot de passe modifié !',
    passwordMismatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Mot de passe trop court (min. 6 caractères)',
    updateError: 'Erreur lors de la mise à jour.',

    // Courses
    courseCatalogue: 'Catalogue de cours', searchCourse: 'Rechercher…',
    noCourses: 'Aucun cours trouvé', viewCourse: 'Voir le cours →',
    noDescription: 'Aucune description', students: 'élèves',

    // Teachers
    ourTutors: 'Nos tuteurs', searchTutor: 'Rechercher un tuteur…',
    noTutors: 'Aucun tuteur trouvé', bookWith: 'Réserver',
    seeProfile: 'Voir le profil',

    // Sessions
    bookSession: 'Réserver une séance', subject: 'Matière', startTime: 'Début', endTime: 'Fin',
    type: 'Type', private: 'Séance privée', group: 'Séance groupe',
    virtual: 'Virtuelle', real: 'Présentielle',
    reviews: 'Avis des élèves', noReviews: 'Aucun avis pour le moment.',
    back: 'Retour aux tuteurs', perHour: 'par heure', hoursTaught: 'h enseignées',
    availability2: 'Disponibilités', selectSlot: 'Cliquez sur un créneau pour pré-remplir la réservation',
    booking: 'Réservation…', book: 'Réserver la séance', teacher: 'Enseignant',
    mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Jeu', fri: 'Ven', sat: 'Sam', sun: 'Dim',
    confirm: 'Confirmer', reject: 'Refuser', cancel: 'Annuler',
    markComplete: 'Marquer terminé', meetingLink: 'Lien réunion',
    pending: 'En attente', scheduled: 'Programmée', completed: 'Terminée', cancelled: 'Annulée',
    waitingConfirm: 'En attente de confirmation du prof',
    waitingStudent: 'En attente de validation élève',
    waitingTeacher: 'En attente de validation prof',
    bothMustConfirm: 'Prof et élève doivent tous les deux confirmer la fin',
    sessionNotEndedYet: 'La séance n\'est pas encore terminée',
    virtualInfo: 'Séance virtuelle — complétée automatiquement par ncMeet',
    slotUnavailable: 'Ce créneau n\'est pas disponible',
    sessionCreated: 'Demande de séance envoyée au professeur !',
    sessionConfirmed: 'Séance confirmée !',
    sessionRejected: 'Séance refusée',
    sessionCancelled: 'Séance annulée',
    markedComplete: 'Marquée comme terminée de votre côté',
    sessionCompleted: 'Séance terminée !',
    isVirtual: 'Séance virtuelle (lien visio)',
    meetingLinkLabel: 'Lien de visioconférence',
    copyLink: 'Copier', linkCopied: 'Lien copié !',
    joinNcMeet: 'Rejoindre via ncMeet', createRoom: 'Créer la salle ncMeet',
    ncMeetCreated: 'Salle ncMeet créée !', ncMeetError: 'Erreur lors de la création ncMeet',
    openingNcMeet: 'Ouverture de ncMeet…',
    rateSession: 'Noter la séance', yourRating: 'Votre note', yourComment: 'Votre commentaire',
    reviewPlaceholder: 'Partagez votre expérience avec ce professeur…',
    submitReview: 'Envoyer l\'évaluation', reviewSent: 'Évaluation envoyée !',
    reviewError: 'Erreur lors de l\'envoi', alreadyReviewed: 'Déjà évalué',
    cancelReview: 'Annuler',

    // Notifications
    markAllRead: 'Tout marquer comme lu', noNotifications: 'Aucune notification',
    notifSessionConfirmed: 'Séance confirmée', notifSessionRejected: 'Séance refusée',
    notifSessionCancelled: 'Séance annulée', notifSessionCompleted: 'Séance terminée',
    notifNcMeetReady: 'Salle ncMeet prête', viewSession: 'Voir mes séances',
    notifPage: 'Toutes les notifications', notifEmpty: 'Tout est lu !',
    notifEmptyDesc: 'Vous n\'avez aucune notification pour l\'instant.',
    deleteRead: 'Supprimer les lues', filterAll: 'Toutes', filterUnread: 'Non lues',
    filterSessions: 'Séances', filterNcMeet: 'ncMeet',

    // Dashboards
    upcomingSessions: 'Prochaines séances', noUpcomingSessions: 'Aucune séance prévue',
    findTutor: 'Trouver un tuteur', noEnrolledCourses: 'Aucun cours suivi',
    exploreCourses: 'Explorer les cours', quickActions: 'Actions rapides',
    viewAll: 'Voir tout', manage: 'Gérer',
    teacherDashTitle: 'Tableau de bord Enseignant',
    adminTitle: 'Administration', platformOverview: 'Vue d\'ensemble de la plateforme',
    recentUsers: 'Utilisateurs récents', recentSessions: 'Séances récentes',
    noUpcomingTeacher: 'Aucune séance à venir', noCourseTeacher: 'Aucun cours',
    helloUser: 'Bonjour', yourDashboard: 'Voici votre tableau de bord',

    // AI
    aiSubtitle: 'Posez vos questions, générez des tests ou corrigez vos devoirs',
    chatTab: '💬 Chat IA', testTab: '📝 Générer test', homeworkTab: '✏️ Corriger devoir',
    aiGreeting: 'Bonjour ! Je suis votre tuteur IA.',
    aiGreetingSub: 'Posez-moi n\'importe quelle question sur vos cours.',
    sendMessage: 'Envoyer', chatPlaceholder: 'Posez votre question…',
    generateTestBtn: '🎯 Générer le test', generatingTest: 'Génération en cours…',
    correctHomeworkBtn: '✏️ Corriger', correcting: 'Correction en cours…',
    generateTestTitle: 'Générer un test', correctHomeworkTitle: 'Correction de devoir',
    numQuestions: 'Nombre de questions', difficulty: 'Difficulté',
    easy: 'Facile', medium: 'Moyen', hard: 'Difficile',
    level: 'Niveau', yourHomework: 'Votre devoir (texte)',
    homeworkPlaceholder: 'Collez votre devoir ici…',
    aiError: 'Désolé, une erreur s\'est produite. Réessayez.',
    enterHomework: 'Veuillez saisir votre devoir',
    generationError: 'Erreur lors de la génération',
    correctionError: 'Erreur lors de la correction',

    adminNotifTitle: 'Envoyer une notification', broadcastHistory: 'Historique des envois',
    audienceAll: 'Tout le monde', audienceTeachers: 'Enseignants', audienceStudents: 'Élèves',
    audienceParents: 'Parents', audienceAdmins: 'Administrateurs', audiencePrivate: 'Privé (1 utilisateur)',
    selectUser: 'Choisir un utilisateur', sendNotif: 'Envoyer', notifSent: 'Notification envoyée !',
    broadcastType: 'Type de message', adminBroadcastLabel: 'Annonce admin',
    recipientCount: 'destinataires', adminNotifications: 'Notifications admin',
    filterBroadcast: 'Annonces', notifBroadcastLabel: 'Annonce',

    // Email verification
    checkYourEmail: 'Vérifiez votre email', emailVerifSent: 'Un lien de confirmation vous a été envoyé.',
    emailVerifSuccess: 'Email vérifié ! Bienvenue sur EduPlatform.',
    emailVerifError: 'Lien invalide ou expiré.',
    emailNotVerified: 'Veuillez vérifier votre adresse email avant de vous connecter.',

    // Education system
    educationSystem: 'Système éducatif', selectEduSystem: 'Choisir un système',
    selectLevel: '— Niveau —',
    tunisian: 'Système Tunisien', french: 'Système Français',
    american: 'Système Américain', british: 'Système Britannique',

    // Teacher profile
    teacherPublicProfile: 'Profil public enseignant',
    teacherProfileSubtitle: 'Ces informations sont visibles par les élèves.',
    professionalTitle: 'Titre professionnel', teacherDescription: 'Description',
    profileImageUrl: 'Photo de profil (URL)',
    teacherSkills: 'Compétences', addSkill: 'Ajouter une compétence',
    teacherEducations: 'Formation académique', addEducation: 'Ajouter une formation',
    teacherExperiences: 'Expériences', addExperience: 'Ajouter une expérience',
    subjectsTaught: 'Matières enseignées',
    saveTeacherProfile: 'Sauvegarder le profil',
    teacherProfileSaved: 'Profil enseignant mis à jour !',
  },
  en: {
    teachers: 'Tutors', courses: 'Courses', login: 'Login', register: 'Sign up',
    dashboard: 'Dashboard', logout: 'Sign out', profile: 'Profile', sessions: 'My sessions',
    myCourses: 'My courses', availability: 'Availability', users: 'Users',
    aiTutor: 'AI Tutor', home: 'Home', notifications: 'Notifications',

    heroTagline: 'France\'s #1 tutoring platform',
    heroTitle1: 'Master your future', heroTitle2: 'with an', heroTitle3: 'expert tutor',
    heroSubtitle: 'Connect with qualified teachers for personalised sessions. Because every student deserves to reach their full potential.',
    startFree: 'Get started free', seeTutors: 'See tutors',
    verifiedTeachers: 'Verified teachers', flexibleHours: 'Flexible hours', provenResults: 'Proven results',
    whyChoose: 'Why choose EduPlatform?', whySubtitle: 'A complete, personalised and effective learning experience.',
    ctaTitle: 'Ready to start?', ctaSubtitle: 'Join thousands of students progressing with EduPlatform.',
    createFreeAccount: 'Create a free account',
    allRights: 'All rights reserved.',

    welcome: 'Welcome', loginSubtitle: 'Sign in to your account',
    password: 'Password', signIn: 'Sign in', signingIn: 'Signing in…',
    noAccount: 'No account?', signUpLink: 'Sign up',
    demoAccountsLabel: 'Demo accounts:',
    invalidCredentials: 'Invalid email or password.',
    fillFields: 'Please fill all fields.',
    loginSuccess: 'Signed in successfully!',

    createAccount: 'Create an account', joinToday: 'Join EduPlatform today',
    firstName: 'First name', lastName: 'Last name',
    iAm: 'I am a', studentRole: 'Student', teacherRole: 'Teacher / Tutor', parentRole: 'Parent',
    creating: 'Creating…', createMyAccount: 'Create my account',
    alreadyMember: 'Already a member?', signInLink: 'Sign in',
    minChars: 'Min. 8 characters', accountCreated: 'Account created successfully!',

    myProfile: 'My profile', profileSubtitle: 'Manage your personal information',
    personalInfo: 'Personal information',
    phoneNumber: 'Phone', biography: 'Biography',
    bioPlaceholder: 'Tell us about yourself…',
    saving: 'Saving…', save: 'Save',
    profileUpdated: '✓ Profile updated successfully',
    changePassword: 'Change password', newPassword: 'New password',
    confirmPassword: 'Confirm', repeatPassword: 'Repeat password',
    changeBtn: 'Change', passwordChanged: 'Password changed!',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password too short (min. 6 characters)',
    updateError: 'Error updating profile.',

    courseCatalogue: 'Course catalogue', searchCourse: 'Search…',
    noCourses: 'No courses found', viewCourse: 'View course →',
    noDescription: 'No description', students: 'students',

    ourTutors: 'Our tutors', searchTutor: 'Search for a tutor…',
    noTutors: 'No tutors found', bookWith: 'Book',
    seeProfile: 'See profile',

    bookSession: 'Book a session', subject: 'Subject', startTime: 'Start time', endTime: 'End time',
    type: 'Type', private: 'Private session', group: 'Group session',
    virtual: 'Virtual', real: 'In-person',
    reviews: 'Student reviews', noReviews: 'No reviews yet.',
    back: 'Back to tutors', perHour: 'per hour', hoursTaught: 'h taught',
    availability2: 'Availability', selectSlot: 'Click a slot to pre-fill the booking form',
    booking: 'Booking…', book: 'Book session', teacher: 'Teacher',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    confirm: 'Confirm', reject: 'Reject', cancel: 'Cancel',
    markComplete: 'Mark complete', meetingLink: 'Meeting link',
    pending: 'Pending', scheduled: 'Scheduled', completed: 'Completed', cancelled: 'Cancelled',
    waitingConfirm: 'Waiting for teacher confirmation',
    waitingStudent: 'Waiting for student validation',
    waitingTeacher: 'Waiting for teacher validation',
    bothMustConfirm: 'Both teacher and student must confirm completion',
    sessionNotEndedYet: 'The session has not ended yet',
    virtualInfo: 'Virtual session — automatically completed by ncMeet',
    slotUnavailable: 'This slot is not available',
    sessionCreated: 'Session request sent to teacher!',
    sessionConfirmed: 'Session confirmed!',
    sessionRejected: 'Session rejected',
    sessionCancelled: 'Session cancelled',
    markedComplete: 'Marked as complete on your side',
    sessionCompleted: 'Session completed!',
    isVirtual: 'Virtual session (video link)',
    meetingLinkLabel: 'Video conference link',
    copyLink: 'Copy', linkCopied: 'Link copied!',
    joinNcMeet: 'Join via ncMeet', createRoom: 'Create ncMeet room',
    ncMeetCreated: 'ncMeet room created!', ncMeetError: 'ncMeet creation error',
    openingNcMeet: 'Opening ncMeet…',
    rateSession: 'Rate this session', yourRating: 'Your rating', yourComment: 'Your comment',
    reviewPlaceholder: 'Share your experience with this teacher…',
    submitReview: 'Submit review', reviewSent: 'Review sent!',
    reviewError: 'Error sending review', alreadyReviewed: 'Already reviewed',
    cancelReview: 'Cancel',

    markAllRead: 'Mark all as read', noNotifications: 'No notifications',
    notifSessionConfirmed: 'Session confirmed', notifSessionRejected: 'Session rejected',
    notifSessionCancelled: 'Session cancelled', notifSessionCompleted: 'Session completed',
    notifNcMeetReady: 'ncMeet room ready', viewSession: 'View my sessions',
    notifPage: 'All notifications', notifEmpty: 'All caught up!',
    notifEmptyDesc: 'You have no notifications at the moment.',
    deleteRead: 'Delete read', filterAll: 'All', filterUnread: 'Unread',
    filterSessions: 'Sessions', filterNcMeet: 'ncMeet',

    upcomingSessions: 'Upcoming sessions', noUpcomingSessions: 'No upcoming sessions',
    findTutor: 'Find a tutor', noEnrolledCourses: 'No enrolled courses',
    exploreCourses: 'Explore courses', quickActions: 'Quick actions',
    viewAll: 'View all', manage: 'Manage',
    teacherDashTitle: 'Teacher Dashboard',
    adminTitle: 'Administration', platformOverview: 'Platform overview',
    recentUsers: 'Recent users', recentSessions: 'Recent sessions',
    noUpcomingTeacher: 'No upcoming sessions', noCourseTeacher: 'No courses',
    helloUser: 'Hello', yourDashboard: 'Here is your dashboard',

    aiSubtitle: 'Ask questions, generate tests or correct your homework',
    chatTab: '💬 AI Chat', testTab: '📝 Generate test', homeworkTab: '✏️ Correct homework',
    aiGreeting: 'Hello! I am your AI tutor.',
    aiGreetingSub: 'Ask me any question about your courses.',
    sendMessage: 'Send', chatPlaceholder: 'Ask your question…',
    generateTestBtn: '🎯 Generate test', generatingTest: 'Generating…',
    correctHomeworkBtn: '✏️ Correct', correcting: 'Correcting…',
    generateTestTitle: 'Generate a test', correctHomeworkTitle: 'Homework correction',
    numQuestions: 'Number of questions', difficulty: 'Difficulty',
    easy: 'Easy', medium: 'Medium', hard: 'Hard',
    level: 'Level', yourHomework: 'Your homework (text)',
    homeworkPlaceholder: 'Paste your homework here…',
    aiError: 'Sorry, an error occurred. Please try again.',
    enterHomework: 'Please enter your homework',
    generationError: 'Error generating test',
    correctionError: 'Error correcting homework',

    adminNotifTitle: 'Send a notification', broadcastHistory: 'Broadcast history',
    audienceAll: 'Everyone', audienceTeachers: 'Teachers', audienceStudents: 'Students',
    audienceParents: 'Parents', audienceAdmins: 'Admins', audiencePrivate: 'Private (1 user)',
    selectUser: 'Select a user', sendNotif: 'Send', notifSent: 'Notification sent!',
    broadcastType: 'Message type', adminBroadcastLabel: 'Admin announcement',
    recipientCount: 'recipients', adminNotifications: 'Admin notifications',
    filterBroadcast: 'Announcements', notifBroadcastLabel: 'Announcement',
  },
  ar: {
    teachers: 'المدرسون', courses: 'الدروس', login: 'دخول', register: 'تسجيل',
    dashboard: 'لوحة التحكم', logout: 'خروج', profile: 'الملف الشخصي', sessions: 'جلساتي',
    myCourses: 'دروسي', availability: 'التوفر', users: 'المستخدمون',
    aiTutor: 'المدرس الذكي', home: 'الرئيسية', notifications: 'الإشعارات',

    heroTagline: 'منصة الدعم المدرسي رقم 1 في فرنسا',
    heroTitle1: 'أتقن مستقبلك', heroTitle2: 'مع', heroTitle3: 'مدرس خبير',
    heroSubtitle: 'تواصل مع معلمين مؤهلين لجلسات مخصصة. لأن كل طالب يستحق الوصول إلى أقصى إمكاناته.',
    startFree: 'ابدأ مجاناً', seeTutors: 'عرض المدرسين',
    verifiedTeachers: 'مدرسون موثقون', flexibleHours: 'مواعيد مرنة', provenResults: 'نتائج مثبتة',
    whyChoose: 'لماذا EduPlatform؟', whySubtitle: 'تجربة تعلم متكاملة، مخصصة وفعّالة.',
    ctaTitle: 'هل أنت مستعد للبدء؟', ctaSubtitle: 'انضم لآلاف الطلاب الذين يتقدمون مع EduPlatform.',
    createFreeAccount: 'إنشاء حساب مجاني',
    allRights: 'جميع الحقوق محفوظة.',

    welcome: 'مرحباً', loginSubtitle: 'تسجيل الدخول إلى حسابك',
    password: 'كلمة المرور', signIn: 'تسجيل الدخول', signingIn: 'جاري الدخول...',
    noAccount: 'ليس لديك حساب؟', signUpLink: 'إنشاء حساب',
    demoAccountsLabel: 'حسابات تجريبية:',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    fillFields: 'يرجى ملء جميع الحقول.',
    loginSuccess: 'تم تسجيل الدخول بنجاح!',

    createAccount: 'إنشاء حساب', joinToday: 'انضم إلى EduPlatform اليوم',
    firstName: 'الاسم', lastName: 'اللقب',
    iAm: 'أنا', studentRole: 'طالب', teacherRole: 'مدرس', parentRole: 'ولي الأمر',
    creating: 'جاري الإنشاء...', createMyAccount: 'إنشاء حسابي',
    alreadyMember: 'لديك حساب بالفعل؟', signInLink: 'تسجيل الدخول',
    minChars: 'الحد الأدنى 8 أحرف', accountCreated: 'تم إنشاء الحساب بنجاح!',

    myProfile: 'ملفي الشخصي', profileSubtitle: 'إدارة معلوماتك الشخصية',
    personalInfo: 'المعلومات الشخصية',
    phoneNumber: 'رقم الهاتف', biography: 'السيرة الذاتية',
    bioPlaceholder: 'أخبرنا عن نفسك...',
    saving: 'جاري الحفظ...', save: 'حفظ',
    profileUpdated: '✓ تم تحديث الملف الشخصي بنجاح',
    changePassword: 'تغيير كلمة المرور', newPassword: 'كلمة مرور جديدة',
    confirmPassword: 'تأكيد', repeatPassword: 'تكرار كلمة المرور',
    changeBtn: 'تغيير', passwordChanged: 'تم تغيير كلمة المرور!',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    passwordTooShort: 'كلمة المرور قصيرة جداً (الحد الأدنى 6 أحرف)',
    updateError: 'خطأ في تحديث الملف الشخصي.',

    courseCatalogue: 'كتالوج الدورات', searchCourse: 'بحث...',
    noCourses: 'لا توجد دورات', viewCourse: '← عرض الدورة',
    noDescription: 'لا يوجد وصف', students: 'طلاب',

    ourTutors: 'مدرسونا', searchTutor: 'ابحث عن مدرس...',
    noTutors: 'لا يوجد مدرسون', bookWith: 'حجز',
    seeProfile: 'عرض الملف',

    bookSession: 'حجز جلسة', subject: 'المادة', startTime: 'البداية', endTime: 'النهاية',
    type: 'النوع', private: 'جلسة خاصة', group: 'جلسة جماعية',
    virtual: 'افتراضية', real: 'حضورية',
    reviews: 'آراء الطلاب', noReviews: 'لا توجد آراء بعد.',
    back: 'العودة للمدرسين', perHour: 'في الساعة', hoursTaught: 'ساعة',
    availability2: 'التوفر', selectSlot: 'انقر على موعد لملء نموذج الحجز',
    booking: 'جاري الحجز...', book: 'حجز الجلسة', teacher: 'مدرس',
    mon: 'الإثنين', tue: 'الثلاثاء', wed: 'الأربعاء', thu: 'الخميس', fri: 'الجمعة', sat: 'السبت', sun: 'الأحد',
    confirm: 'تأكيد', reject: 'رفض', cancel: 'إلغاء',
    markComplete: 'تحديد كمكتملة', meetingLink: 'رابط الاجتماع',
    pending: 'قيد الانتظار', scheduled: 'مجدولة', completed: 'مكتملة', cancelled: 'ملغاة',
    waitingConfirm: 'في انتظار تأكيد المدرس',
    waitingStudent: 'في انتظار تأكيد الطالب',
    waitingTeacher: 'في انتظار تأكيد المدرس',
    bothMustConfirm: 'يجب على المدرس والطالب تأكيد الإنهاء',
    sessionNotEndedYet: 'لم تنتهِ الجلسة بعد',
    virtualInfo: 'جلسة افتراضية — تُكتمل تلقائياً عبر ncMeet',
    slotUnavailable: 'هذا الوقت غير متاح',
    sessionCreated: 'تم إرسال طلب الجلسة إلى المدرس!',
    sessionConfirmed: 'تم تأكيد الجلسة!',
    sessionRejected: 'تم رفض الجلسة',
    sessionCancelled: 'تم إلغاء الجلسة',
    markedComplete: 'تم التحديد كمكتملة من جانبك',
    sessionCompleted: 'اكتملت الجلسة!',
    isVirtual: 'جلسة افتراضية (رابط فيديو)',
    meetingLinkLabel: 'رابط مؤتمر الفيديو',
    copyLink: 'نسخ', linkCopied: 'تم نسخ الرابط!',
    joinNcMeet: 'الانضمام عبر ncMeet', createRoom: 'إنشاء غرفة ncMeet',
    ncMeetCreated: 'تم إنشاء غرفة ncMeet!', ncMeetError: 'خطأ في إنشاء ncMeet',
    openingNcMeet: 'جاري فتح ncMeet…',
    rateSession: 'تقييم الجلسة', yourRating: 'تقييمك', yourComment: 'تعليقك',
    reviewPlaceholder: 'شاركنا تجربتك مع هذا المعلم…',
    submitReview: 'إرسال التقييم', reviewSent: 'تم إرسال التقييم!',
    reviewError: 'خطأ في إرسال التقييم', alreadyReviewed: 'تم التقييم',
    cancelReview: 'إلغاء',

    markAllRead: 'تحديد الكل كمقروء', noNotifications: 'لا توجد إشعارات',
    notifSessionConfirmed: 'تم تأكيد الجلسة', notifSessionRejected: 'تم رفض الجلسة',
    notifSessionCancelled: 'تم إلغاء الجلسة', notifSessionCompleted: 'اكتملت الجلسة',
    notifNcMeetReady: 'غرفة ncMeet جاهزة', viewSession: 'عرض جلساتي',
    notifPage: 'جميع الإشعارات', notifEmpty: 'أنت مواكب للكل!',
    notifEmptyDesc: 'ليس لديك أي إشعارات في الوقت الحالي.',
    deleteRead: 'حذف المقروءة', filterAll: 'الكل', filterUnread: 'غير مقروء',
    filterSessions: 'الجلسات', filterNcMeet: 'ncMeet',

    upcomingSessions: 'الجلسات القادمة', noUpcomingSessions: 'لا توجد جلسات قادمة',
    findTutor: 'ابحث عن مدرس', noEnrolledCourses: 'لا توجد دورات مسجلة',
    exploreCourses: 'استكشف الدورات', quickActions: 'إجراءات سريعة',
    viewAll: 'عرض الكل', manage: 'إدارة',
    teacherDashTitle: 'لوحة تحكم المدرس',
    adminTitle: 'الإدارة', platformOverview: 'نظرة عامة على المنصة',
    recentUsers: 'المستخدمون الأخيرون', recentSessions: 'الجلسات الأخيرة',
    noUpcomingTeacher: 'لا توجد جلسات قادمة', noCourseTeacher: 'لا توجد دورات',
    helloUser: 'مرحباً', yourDashboard: 'هذه لوحة تحكمك',

    aiSubtitle: 'اطرح أسئلتك، أنشئ اختبارات أو صحح واجباتك',
    chatTab: '💬 دردشة ذكية', testTab: '📝 إنشاء اختبار', homeworkTab: '✏️ تصحيح الواجب',
    aiGreeting: 'مرحباً! أنا مدرسك الذكي.',
    aiGreetingSub: 'اسألني أي سؤال حول دروسك.',
    sendMessage: 'إرسال', chatPlaceholder: 'اطرح سؤالك…',
    generateTestBtn: '🎯 إنشاء الاختبار', generatingTest: 'جاري الإنشاء...',
    correctHomeworkBtn: '✏️ تصحيح', correcting: 'جاري التصحيح...',
    generateTestTitle: 'إنشاء اختبار', correctHomeworkTitle: 'تصحيح الواجب',
    numQuestions: 'عدد الأسئلة', difficulty: 'الصعوبة',
    easy: 'سهل', medium: 'متوسط', hard: 'صعب',
    level: 'المستوى', yourHomework: 'واجبك (نص)',
    homeworkPlaceholder: 'الصق واجبك هنا...',
    aiError: 'عذراً، حدث خطأ. يرجى المحاولة مجدداً.',
    enterHomework: 'يرجى إدخال واجبك',
    generationError: 'خطأ في إنشاء الاختبار',
    correctionError: 'خطأ في تصحيح الواجب',

    adminNotifTitle: 'إرسال إشعار', broadcastHistory: 'سجل الإرسال',
    audienceAll: 'الجميع', audienceTeachers: 'المدرسون', audienceStudents: 'الطلاب',
    audienceParents: 'الأولياء', audienceAdmins: 'المديرون', audiencePrivate: 'خاص (مستخدم واحد)',
    selectUser: 'اختر مستخدماً', sendNotif: 'إرسال', notifSent: 'تم إرسال الإشعار!',
    broadcastType: 'نوع الرسالة', adminBroadcastLabel: 'إعلان المشرف',
    recipientCount: 'مستلم', adminNotifications: 'إشعارات المشرف',
    filterBroadcast: 'الإعلانات', notifBroadcastLabel: 'إعلان',
  }
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private _lang = signal<Lang>((localStorage.getItem('edu_lang') as Lang) ?? 'fr');
  readonly lang  = this._lang.asReadonly();
  readonly t     = computed(() => T[this._lang()]);
  readonly isRtl = computed(() => this._lang() === 'ar');

  init() { this.applyDir(this._lang()); }

  private applyDir(lang: Lang) {
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang);
  }

  setLang(lang: Lang) {
    this._lang.set(lang);
    localStorage.setItem('edu_lang', lang);
    this.applyDir(lang);
  }

  toggle() {
    const order: Lang[] = ['fr', 'en', 'ar'];
    const idx = order.indexOf(this._lang());
    this.setLang(order[(idx + 1) % order.length]);
  }
}
